#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Brian
nitrogen --restore &
$HOME/.config/polybar/launch.sh

# Monitor
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

# Color settings
bspc config normal_border_color "#44475A"
bspc config active_border_color "#8ABEB7"
bspc config focused_border_color "#00FFFF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
